services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    env_file: .env
    restart: always
    expose:
      - "3306"
    volumes:
      - mariadbVol:/var/lib/mysql
    secrets:
      - db_password
      - db_root_password
    networks:
      - inception

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    expose:
      - "9000"
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - wordpressVol:/var/www/html
    networks:
      - inception
    restart: always
    secrets:
      - db_password
      - db_root_password
      - wp_admin_password
      - wp_user_password

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    env_file: .env
    volumes:
      - wordpressVol:/var/www/html
    networks:
      - inception
    restart: always

networks:
  inception:
    driver: bridge

volumes:
  mariadbVol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/numancan/data/mariadb
  wordpressVol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/numancan/data/wordpress

secrets:
  wp_admin_password:
    file: ./../secrets/wp_admin_password.txt
  wp_user_password:
    file: ./../secrets/wp_user_password.txt
  db_root_password:
    file: ./../secrets/db_root_password.txt
  db_password:
    file: ./../secrets/db_password.txt